#!/usr/bin/env node
// Copyright 2026, Pulumi Corporation. All rights reserved.
/**
 * Build SCSS and Tailwind outputs from layered token JSON sources.
 *
 * Source of truth:
 *   tokens/core/primitives.json      — shared console/docs palette
 *   tokens/console/extensions.json   — console-only (e.g. aqua)
 *   tokens/marketing/extensions.json — marketing-only (salmon, fuchsia, legacy gray)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const GENERATED = path.join(ROOT, "generated");

const HEADER = `// Copyright 2026, Pulumi Corporation. All rights reserved.
// GENERATED BY scripts/build-tokens.mjs — DO NOT EDIT BY HAND.
`;

function readJson(relativePath) {
    return JSON.parse(fs.readFileSync(path.join(ROOT, relativePath), "utf8"));
}

function mergeConsolePalettes() {
    const core = readJson("tokens/core/primitives.json");
    const consoleExt = readJson("tokens/console/extensions.json");
    return {
        white: core.white,
        black: core.black,
        palettes: { ...core.palettes, ...consoleExt.palettes },
        product: "console",
    };
}

function readMarketingTokens() {
    return readJson("tokens/marketing/extensions.json");
}

function resolveBrandRefs(value, brand) {
    if (typeof value !== "string") return value;
    const match = value.match(/^\{brand\.([a-z-]+)\}$/);
    if (!match) return value;
    const key = match[1];
    if (!(key in brand)) {
        throw new Error(`Unknown brand reference: ${value}`);
    }
    return brand[key];
}

function resolvePalette(palette, brand) {
    const resolved = {};
    for (const [shade, value] of Object.entries(palette)) {
        resolved[shade] = resolveBrandRefs(value, brand);
    }
    return resolved;
}

/** @param {Record<string, Record<string, string>>} palettes */
function scssPaletteMap(family, palette) {
    const lines = Object.entries(palette)
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([shade, hex]) => `    ${shade}: ${hex},`);
    return `$${family}: (\n${lines.join("\n")}\n);`;
}

function scssBrandMap(brand) {
    const lines = Object.entries(brand).map(([key, hex]) => `    "${key}": ${hex},`);
    return `$brand: (\n${lines.join("\n")}\n);`;
}

function generateConsolePrimitivePalettesScss(consoleTokens) {
    const families = Object.keys(consoleTokens.palettes).sort();
    const maps = families.map((f) => scssPaletteMap(f, consoleTokens.palettes[f]));

    const colorsEntries = families.map((f) => `    "${f}": $${f},`).join("\n");

    return `${HEADER}
@use "sass:map";

$white: ${consoleTokens.white};
$black: ${consoleTokens.black};

${maps.join("\n\n")}

$colors: (
${colorsEntries}
);
$single-colors: (
    "white": $white,
    "black": $black,
);
$color-shades: 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000;
`;
}

function generateConsoleTailwindV4ThemeScss(consoleTokens) {
    const { palettes, white, black } = consoleTokens;
    const lines = [
        `${HEADER}
// Tailwind v4 @theme — console/docs palette from tokens/core + tokens/console.
@theme {
    --color-white: ${white};
    --color-black: ${black};
    --color-service-black: ${palettes.gray["1000"]};
    --color-transparent: transparent;
`,
    ];

    for (const [family, scale] of Object.entries(palettes)) {
        for (const [shade, value] of Object.entries(scale)) {
            const twShade = shade === "1000" ? "950" : shade;
            lines.push(`    --color-${family}-${twShade}: ${value};`);
        }
    }

    const s = {
        violet: palettes.violet,
        gray: palettes.gray,
        yellow: palettes.yellow,
        blue: palettes.blue,
        red: palettes.red,
        orange: palettes.orange,
        green: palettes.green,
    };

    lines.push("");
    lines.push(`    --color-violet-primary: ${s.violet["700"]};`);
    lines.push("");
    lines.push(`    --color-violet-background: ${s.violet["50"]};`);
    lines.push(`    --color-violet-muted: ${s.violet["200"]};`);
    lines.push(`    --color-violet-accent: ${s.violet["500"]};`);
    lines.push("");
    lines.push(`    --color-gray-background: ${s.gray["50"]};`);
    lines.push(`    --color-gray-muted: ${s.gray["200"]};`);
    lines.push(`    --color-gray-accent: ${s.gray["500"]};`);
    lines.push(`    --color-gray-primary: ${s.gray["700"]};`);
    lines.push("");
    lines.push(`    --color-yellow-background: ${s.yellow["50"]};`);
    lines.push(`    --color-yellow-muted: ${s.yellow["200"]};`);
    lines.push(`    --color-yellow-accent: ${s.yellow["500"]};`);
    lines.push(`    --color-yellow-primary: ${s.yellow["700"]};`);
    lines.push("");
    lines.push(`    --color-blue-background: ${s.blue["50"]};`);
    lines.push(`    --color-blue-muted: ${s.blue["200"]};`);
    lines.push(`    --color-blue-accent: ${s.blue["500"]};`);
    lines.push(`    --color-blue-primary: ${s.blue["700"]};`);
    lines.push("");
    lines.push(`    --color-red-background: ${s.red["50"]};`);
    lines.push(`    --color-red-muted: ${s.red["200"]};`);
    lines.push(`    --color-red-accent: ${s.red["500"]};`);
    lines.push(`    --color-red-primary: ${s.red["700"]};`);
    lines.push("");
    lines.push(`    --color-orange-background: ${s.orange["50"]};`);
    lines.push(`    --color-orange-muted: ${s.orange["200"]};`);
    lines.push(`    --color-orange-accent: ${s.orange["500"]};`);
    lines.push(`    --color-orange-primary: ${s.orange["700"]};`);
    lines.push("");
    lines.push(`    --color-green-background: ${s.green["50"]};`);
    lines.push(`    --color-green-muted: ${s.green["200"]};`);
    lines.push(`    --color-green-accent: ${s.green["500"]};`);
    lines.push(`    --color-green-primary: ${s.green["700"]};`);
    lines.push("");
    lines.push(`    --font-display: Inter, ui-sans-serif, system-ui, sans-serif;`);
    lines.push(`    --font-body: Inter, ui-sans-serif, system-ui, sans-serif;`);
    lines.push(`    --font-mono: "Monaspace Neon Var", ui-monospace, SFMono-Regular, monospace;`);
    lines.push(`    --default-font-feature-settings: "liga" 1, "calt" 1, "cv11" 1;`);
    lines.push("");
    lines.push(`    --breakpoint-sm: 640px;`);
    lines.push(`    --breakpoint-md: 768px;`);
    lines.push(`    --breakpoint-lg: 1024px;`);
    lines.push(`    --breakpoint-xl: 1280px;`);
    lines.push(`    --breakpoint-xxl: 1536px;`);
    lines.push(`    --shadow-3xl: 0 35px 70px -20px rgba(0, 0, 0, 0.5);`);
    lines.push(`    --leading-extra-tight: 1.1;`);
    lines.push("}");

    return lines.join("\n");
}

function generateMarketingWwwColorsScss(marketing) {
    const brand = marketing.brand;
    const resolvedPalettes = {};
    for (const [family, palette] of Object.entries(marketing.palettes)) {
        resolvedPalettes[family] = resolvePalette(palette, brand);
    }

    const brandAliases = [
        "yellow",
        "salmon",
        "fuchsia",
        "purple",
        "violet",
        "blue",
    ]
        .map((key) => `$brand-${key}: map.get($brand, "${key}");`)
        .join("\n");

    const paletteMaps = Object.entries(resolvedPalettes)
        .map(([family, palette]) => scssPaletteMap(family, palette))
        .join("\n\n");

    return `${HEADER}
@use "sass:map";

$black: #000;
$white: #fff;

${scssBrandMap(brand)}

${brandAliases}

${paletteMaps}
`;
}

function generateLegacyWwwJson(marketing) {
    const meta = readJson("tokens/marketing/meta.json");
    const brand = {};
    for (const [key, hex] of Object.entries(marketing.brand)) {
        brand[key] = { value: hex, type: "color" };
    }

    const colors = { brand: {} };
    for (const [key, entry] of Object.entries(brand)) {
        colors.brand[key] = entry;
    }

    for (const [family, palette] of Object.entries(marketing.palettes)) {
        colors[family] = {};
        const resolved = resolvePalette(palette, marketing.brand);
        for (const [shade, hex] of Object.entries(resolved)) {
            colors[family][shade] = { value: hex, type: "color" };
        }
    }

    // Tailwind v2 legacy gray includes 850 (maps to marketing gray-900 / old www gray-850)
    if (colors.gray?.["900"]) {
        colors.gray["850"] = { value: colors.gray["900"].value, type: "color" };
    }

    return {
        global: {
            colors,
            typography: meta.typography,
            shape: meta.shape,
        },
    };
}

function generateTokenManifest(consoleTokens, marketing) {
    const coreFamilies = new Set(Object.keys(readJson("tokens/core/primitives.json").palettes));
    const consoleOnlyFamilies = new Set(Object.keys(readJson("tokens/console/extensions.json").palettes));
    const marketingFamilies = new Set(Object.keys(marketing.palettes));

    const sharedFamilies = [...coreFamilies].filter((f) => !consoleOnlyFamilies.has(f));
    const marketingOnlyFamilies = [...marketingFamilies].filter(
        (f) => !coreFamilies.has(f) || f === "salmon" || f === "fuchsia" || f === "purple",
    );

    const conflicts = [];
    for (const family of coreFamilies) {
        if (!marketing.palettes[family]) continue;
        const corePalette = consoleTokens.palettes[family];
        const mktPalette = resolvePalette(marketing.palettes[family], marketing.brand);
        for (const shade of Object.keys(corePalette)) {
            if (shade in mktPalette && corePalette[shade].toLowerCase() !== mktPalette[shade].toLowerCase()) {
                conflicts.push({
                    family,
                    shade,
                    core: corePalette[shade],
                    marketing: mktPalette[shade],
                });
            }
        }
    }

    return {
        layers: {
            core: {
                path: "tokens/core/primitives.json",
                families: [...coreFamilies],
            },
            console: {
                path: "tokens/console/extensions.json",
                families: [...consoleOnlyFamilies],
            },
            marketing: {
                path: "tokens/marketing/extensions.json",
                families: [...marketingFamilies],
                brandKeys: Object.keys(marketing.brand),
            },
        },
        summary: {
            coreFamilyCount: coreFamilies.size,
            consoleOnlyFamilyCount: consoleOnlyFamilies.size,
            marketingFamilyCount: marketingFamilies.size,
            sharedFamilyNames: sharedFamilies,
            marketingOnlyFamilyNames: ["salmon", "fuchsia", "purple", "brand"],
            overlappingFamiliesWithDifferentValues: conflicts,
        },
    };
}

function writeGenerated(relativePath, content) {
    const fullPath = path.join(GENERATED, relativePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, content, "utf8");
    console.log(`Wrote generated/${relativePath}`);
}

function main() {
    const consoleTokens = mergeConsolePalettes();
    const marketing = readMarketingTokens();

    writeGenerated("console/_primitive-palettes.scss", generateConsolePrimitivePalettesScss(consoleTokens));
    writeGenerated("console/tailwind-v4/_theme.scss", generateConsoleTailwindV4ThemeScss(consoleTokens));
    writeGenerated("marketing/_www-colors.scss", generateMarketingWwwColorsScss(marketing));
    writeGenerated("token-manifest.json", `${JSON.stringify(generateTokenManifest(consoleTokens, marketing), null, 4)}\n`);

    const wwwJsonPath = path.join(ROOT, "tokens/www.json");
    fs.writeFileSync(wwwJsonPath, `${JSON.stringify(generateLegacyWwwJson(marketing), null, 4)}\n`, "utf8");
    console.log("Wrote tokens/www.json (legacy Tailwind v2 compat, generated)");

    const conflicts = generateTokenManifest(consoleTokens, marketing).summary.overlappingFamiliesWithDifferentValues;
    if (conflicts.length > 0) {
        console.log(`\nToken manifest: ${conflicts.length} core/marketing palette conflicts (expected for legacy www):`);
        for (const c of conflicts.slice(0, 5)) {
            console.log(`  ${c.family}-${c.shade}: core=${c.core} marketing=${c.marketing}`);
        }
        if (conflicts.length > 5) console.log(`  ... and ${conflicts.length - 5} more`);
    }
}

main();
